//! THIS FILE IS AUTOGENERATED, DO NOT MODIFY
//! When building, `cargo-leptos` generates this file based on
//! the `index.html` file specified in the Config.toml

/// html up to the marker: `<!-- INJECT HEAD -->`
pub const START: &str = r##"
--- START ---
"##;

/// html starting with: `<!-- INJECT HEAD -->`
/// up to: `<!-- INJECT BODY -->`
pub const MIDDLE: &str = r##"
--- MIDDLE ---
"##;

/// html starting with: `<!-- INJECT BODY -->` until the end
pub const END: &str = r##"
--- END ---
"##;

pub fn build_html(head_fn: impl Fn() -> String, body_fn: impl Fn() -> String) -> String {
    format!("{START}{}{MIDDLE}{}{END}", head_fn(), body_fn())
}
